# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_test', '0002_auto_20170223_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='blank@example.com', max_length=30),
        ),
    ]
